// 错误码与后端 backend/src/constants/errorCodes.go 对应。
export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID: "AUTH_INVALID",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  PLAN_CONFLICT: "PLAN_CONFLICT",
  BOOKING_CONFLICT: "BOOKING_CONFLICT",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  INTERNAL: "INTERNAL",
  // 逐项冲突码
  RESOURCE_TIME_OVERLAP: "RESOURCE_TIME_OVERLAP",
  RESOURCE_MAINTENANCE: "RESOURCE_MAINTENANCE",
  RESOURCE_OFFLINE: "RESOURCE_OFFLINE",
  RESOURCE_WINDOW_UNAVAILABLE: "RESOURCE_WINDOW_UNAVAILABLE",
  TASK_DEADLINE_CONFLICT: "TASK_DEADLINE_CONFLICT",
  NO_MATCHING_RESOURCE: "NO_MATCHING_RESOURCE",
  BOOKING_BUMPED: "BOOKING_BUMPED"
} as const;

export const CONFLICT_CODE_TEXT: Record<string, string> = {
  RESOURCE_TIME_OVERLAP: "资源时段重叠",
  RESOURCE_MAINTENANCE: "资源维护中",
  RESOURCE_OFFLINE: "资源离线",
  RESOURCE_WINDOW_UNAVAILABLE: "可用时段不覆盖",
  TASK_DEADLINE_CONFLICT: "任务截止冲突",
  NO_MATCHING_RESOURCE: "无匹配资源",
  BOOKING_BUMPED: "预约被挤出"
};
