export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  PLAN_CONFLICT: "PLAN_CONFLICT",
  BOOKING_CONFLICT: "BOOKING_CONFLICT",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;
